---
apiVersion: v1
kind: Secret
metadata:
  name: elastic
  namespace: kube-system
type: Opaque
data:
  # All values need to be encode by the following command with the '-n' option
  # echo -n 'STRING-TO-ENCODE' | base64
  
  # 192.168.1.4 -> MTkyLjE2OC4xLjQ=
  ELASTICSEARCH_HOST: MTkyLjE2OC4xLjQ=
  #9200
  ELASTICSEARCH_PORT: OTIwMA==
  KIBANA_HOST: MTkyLjE2OC4xLjM=
  # welcome1
  MYSQL_ROOT_PASSWORD: d2VsY29tZTE=
  #elastic
  ELASTIC_USERNAME: ZWxhc3RpYw==
  #changeme
  ELASTIC_PASSWORD: Y2hhbmdlbWU=
---
apiVersion: v1
kind: Secret
metadata:
  name: beats-demo
type: Opaque
data:
  # welcome1
  MYSQL_ROOT_PASSWORD: d2VsY29tZTE=
  MYSQL_PASSWORD: d2VsY29tZTE=
