---
apiVersion: v1
kind: Secret
metadata:
  name: elastic
  namespace: kube-system
type: Opaque
data:
  # 90b4d333691b4665ad989bca7369703c.us-east-1.aws.found.io:9243
  ELASTICSEARCH_HOST: OTBiNGQzMzM2OTFiNDY2NWFkOTg5YmNhNzM2OTcwM2MudXMtZWFzdC0xLmF3cy5mb3VuZC5pbw==
  #9243
  ELASTICSEARCH_PORT: OTI0Mw==
  # Make sure you encode this with the "https://" part and "port" included, like this:
  # https://68888b2a38f24a3fa8b3ada68758c784.us-east-1.aws.found.io:9243
  KIBANA_HOST: aHR0cHM6Ly82ODg4OGIyYTM4ZjI0YTNmYThiM2FkYTY4NzU4Yzc4NC51cy1lYXN0LTEuYXdzLmZvdW5kLmlvOjkyNDM=
  # welcome1
  MYSQL_ROOT_PASSWORD: d2VsY29tZTE=
  #elastic
  ELASTICSEARCH_USERNAME: ZWxhc3RpYw==
  #ydio5mzj8Jj7hOvrLxRkHfHz
  ELASTICSEARCH_PASSWORD: eWRpbzVtemo4Smo3aE92ckx4UmtIZkh6
---
apiVersion: v1
kind: Secret
metadata:
  name: beats-demo
type: Opaque
data:
  # welcome1
  MYSQL_ROOT_PASSWORD: d2VsY29tZTE=
  MYSQL_PASSWORD: d2VsY29tZTE=
